# Generated by Django 5.2.8 on 2026-01-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EwasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphone', 'Headphone'), ('earphone', 'Earphone'), ('charger', 'Charger'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('printer', 'Printer'), ('monitor', 'Monitor'), ('router', 'Router')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('working', 'Working'), ('dead', 'Dead')], max_length=10)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('estimated_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='Completed', max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ewasterequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_recycler', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
