# Generated by Django 5.2.8 on 2026-01-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewasterequest',
            name='device_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ewasterequest',
            name='estimated_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ewasterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('VERIFIED', 'Verified by Admin'), ('SCHEDULED', 'Pickup Scheduled'), ('PICKED', 'Picked Up'), ('PAID', 'Payment Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='EwastePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ewaste_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.ewasterequest')),
            ],
        ),
    ]
