# Generated by Django 5.2.8 on 2026-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ewasterequest_device_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewasterequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ewasterequest',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
