# Generated by Django 5.2.8 on 2026-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ewasterequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewasterequest',
            name='item_name',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('battery', 'Battery'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphone', 'Headphone'), ('earphone', 'Earphone'), ('charger', 'Charger'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('printer', 'Printer'), ('monitor', 'Monitor'), ('router', 'Router')], max_length=20),
        ),
    ]
