# Generated by Django 5.2.8 on 2026-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ewasterequest_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
